aws_root_certificate: "<full path to aws certificate>"
aws_endpoint: "<aws endpoint address>"
aws_certificate: "<full path to aws certificate>"
aws_private_key: "<full path to aws private key>"
device_type: "<type of hardware>"
device_name: "<name of device>"
run_type: "fake"
