broker_endpoint: "<endpoint outside aws>"
broker_username: "<username to broker>"
broker_password: "<password to broker>"
ca_certificate: "<full path to ca certificate>"
device_type: "<type of hardware>"
device_name: "<name of device>"
run_type: "fake"